config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm
  root to: "groups#index"

  resources :users, only: [:new]
  resources :points, only: [:create]
  resources :groups, only: [:new, :index, :create] do
    resources :messages, only: [:index, :new, :create]
  end
  namespace :api do
    resources :groups, only: :index, defaults: { format: 'json' }
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{:crossorigin => "anonymous", :integrity => "sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=", :src => "https://code.jquery.com/jquery-3.4.1.js"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zootalk
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Compiled and minified CSS
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css", :rel => "stylesheet"}/
    / Compiled and minified JavaScript
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"}
  %body
    .header
      =link_to "新規登録", new_user_registration_path, class: "new-user" unless user_signed_in?
      =link_to "ログアウト", destroy_user_session_path, method: :delete, class: "new-user" if user_signed_in?
      =link_to "zooTalk", "/", class: "title"
      =link_to "ログイン", new_user_session_path, class: "login"
    = yield
    .mypage
      .mypage-main
        .mypage-main__you
          YOU
        .mypage-main__icon
          = image_tag current_user.icon.image, :size =>'200x200'  if user_signed_in?
        .mypage-main__group
          = link_to "グループを作る", new_group_path if user_signed_in?
          %br/
          - if user_signed_in?
            あなたのポイントは
            %br/
            = "#{current_user.point.point}pt"
    .footer